### PR TITLE
Adding recommendation for smaller binaries

### PR DESCRIPTION
**Pull request by karelbilek**

### CODE REVIEW

**Comment by jpochyla** [comment]
Does panicking still print full stacktraces, even without the symbol table?

**Comment by karelbilek** [comment]
Hm, probably not

**Comment by jpochyla** [comment]
If it does, let's merge it, otherwise not.

**Comment by prusnak** [comment]
Also please use `cd $GOPATH` instead of `cd ~/go`

**Comment by karelbilek** [comment]
I will close this, I am almost sure this does not produce the correct stacktrace because it removes all the debug symbols. Closing this; I will make @prusnak edit in a separate PR

**Comment by prusnak** [comment]
@karel-3d please also include narrowing the targets to `windows/amd64,windows/386,darwin/amd64,linux/amd64,linux/386`

**Pull request closed without merging**
